# Generated by Django 4.0.5 on 2022-06-14 21:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='default.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
