# Generated by Django 4.0.5 on 2022-06-16 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_remove_project_datecreated_and_more'),
    ]

    operations = [
    ]
