# Generated by Django 4.0.5 on 2022-06-17 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_rename_posted_project_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date_posted',
        ),
    ]
