# Generated by Django 4.0.5 on 2022-06-17 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0010_project_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='post',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
