# Generated by Django 4.0.5 on 2022-06-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0012_initial'),
    ]

    operations = [
    ]
