# Generated by Django 4.0.5 on 2022-06-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0013_auto_20220617_0546'),
    ]

    operations = [
    ]
