# Generated by Django 4.0.5 on 2022-06-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0014_auto_20220617_0601'),
    ]

    operations = [
    ]
